### ISSUE TITLE
Main tasks to prepare for publication

### ISSUE THREAD

**Issue by aboucaud** [b-biswas/MADNESS-legacy#115]
**Meta list of tasks to be performed**

- [ ] Add the docs
- [ ] Add clean notebooks
- [ ] Add some tests !!!
- [x] #116
- [x] Remove .gitattributes (in `repo-size-cleanup`)
- [ ] Move scripts and btksims to a different repo
- [ ] Move repo to LSSTDESC GitHub repo ?!
- [ ] #124
- [ ] [GH ACTION] Synchronize the docs creation with readthedocs.com
- [ ] #117
- [ ] [README] Rewrite introduction
- [ ] [README] Add few code examples
- [ ] [README] Add badges 😎️

**Tasks after publication**

- [ ] Add a citation file CFF[^2]
- [ ] [README] Add citation

[^2]: see [docs about citation files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
